version: '3.6'
services:
  datastore:
    command: ["postgres", "-c", "log_statement=all"]
    image: postgres:13
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - '54320:5432'

volumes:
  datastoreData: